apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-clone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nhammern/kubernetes-examples
    targetRevision: HEAD
    path: mysql-wordpress-pd
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-clone