apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: astraapplications.astra.netapp.io
spec:
  group: astra.netapp.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                version:
                  type: string
                name:
                  type: string
                accountID:
                  type: string
                clusterID:
                  type: string
                sourceAppID:
                  type: string
                sourceClusterID:
                  type: string
                namespaceMapping:
                  type: array
                  items:
                    type: object
                    properties:
                      source:
                        type: string
                      destination:
                        type: string
                namespaceScopedResources:
                  type: array
                  items:
                    type: object
                    properties:
                      namespace:
                        type: string
                      labelSelectors:
                        type: array
                        items:
                          type: string
  scope: Cluster     # we have multi-namespace apps 
  names:
    plural: astraapplications
    singular: astraapplication
    kind: AstraApplication
    shortNames:
    - astraapp